### ISSUE TITLE
PROBLEMA DE INSTALACION MERAN 0.10.5

### ISSUE THREAD

**Issue by Emanuel2015** [Desarrollo-CeSPI/meran#53]
Hola soy nuevo en GitHub y estoy tratando de instalar Linux 6.0.4 para usar Meran-UNLP 0.10.5.

**Comment by matiaspagano** [comment]
Emanuel, que distribución de linux estas instalando? 
Se recomienda usar la versión de 32bits de https://www.debian.org/releases/squeeze/
