### ISSUE TITLE
¿Qué dependencias bloquean la actualización del sistema operativo?

### ISSUE THREAD

**Issue by krahser** [Desarrollo-CeSPI/meran#69]
Hola,

@matiaspagano @carbonemiguel podrían decirme, que dependencias bloquean la actualizacion de Debian por favor.

Desde ya muchas gracias.
Saludos.

**Comment by einar-lanfranco** [comment]
Hola krasher, te diría que la versión del perl en principio es el gran problema. Después hay que analizar una a una las librerías de las que depende el soft, pero primero tenes que poder actualizar el perl.
Cuando migre MatFel fue un drama y tenía muchas menos dependencias.

**Comment by krahser** [comment]
Entonces perl ~ 5.10.1-17. Veo que existe una imagen docker con esa version de perl.
`docker pull perl:5.10.1`.
Por lo menos una variante hasta que se actualize el código.
Muchas Gracias @einar-lanfranco.
